// <auto-generated />
using System;
using GamesDatabase.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamesDatabase.Api.Migrations
{
    [DbContext(typeof(GamesDbContext))]
    [Migration("20251206175551_AddSortOrderToGameView")]
    partial class AddSortOrderToGameView
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("GamesDatabase.Api.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<int?>("Completion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completion");

                    b.Property<string>("Cover")
                        .HasColumnType("TEXT")
                        .HasColumnName("cover");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("Critic")
                        .HasColumnType("INTEGER")
                        .HasColumnName("critic");

                    b.Property<string>("Finished")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished");

                    b.Property<int?>("Grade")
                        .HasColumnType("INTEGER")
                        .HasColumnName("grade");

                    b.Property<bool?>("IsCheaperByKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyStoreUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Logo")
                        .HasColumnType("TEXT")
                        .HasColumnName("logo");

                    b.Property<bool>("ModifiedSinceExport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("modified_since_export");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int?>("PlatformId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("platform_id");

                    b.Property<int?>("PlayedStatusId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("played_status_id");

                    b.Property<string>("Released")
                        .HasColumnType("TEXT")
                        .HasColumnName("released");

                    b.Property<decimal?>("Score")
                        .HasColumnType("TEXT")
                        .HasColumnName("score");

                    b.Property<string>("Started")
                        .HasColumnType("TEXT")
                        .HasColumnName("started");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status_id");

                    b.Property<int?>("Story")
                        .HasColumnType("INTEGER")
                        .HasColumnName("story");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.HasIndex("PlayedStatusId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("game", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Models.GameExportCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("CoverDownloaded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("cover_downloaded");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("cover_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("game_id");

                    b.Property<DateTime>("LastExportedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_exported_at");

                    b.Property<bool>("LogoDownloaded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("logo_downloaded");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("logo_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("game_export_cache", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Models.GamePlatform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("#ffffff")
                        .HasColumnName("color");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("game_platform", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Models.GamePlayWith", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("#ffffff")
                        .HasColumnName("color");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("game_play_with", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Models.GamePlayWithMapping", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("game_id");

                    b.Property<int>("PlayWithId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("play_with_id");

                    b.HasKey("GameId", "PlayWithId");

                    b.HasIndex("PlayWithId");

                    b.ToTable("game_play_with_mapping", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Models.GamePlayedStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("#ffffff")
                        .HasColumnName("color");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("game_played_status", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Models.GameStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("#ffffff")
                        .HasColumnName("color");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<int>("StatusType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status_type");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.HasIndex("UserId", "StatusType", "IsDefault")
                        .IsUnique()
                        .HasFilter("is_default = 1");

                    b.ToTable("game_status", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Models.GameView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("FiltersJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("filters_json");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_public");

                    b.Property<bool>("ModifiedSinceExport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("modified_since_export");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SortingJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("sorting_json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("game_view", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Models.GameViewExportCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ConfigurationHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("configuration_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("GameViewId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("game_view_id");

                    b.Property<DateTime>("LastExportedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_exported_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GameViewId")
                        .IsUnique();

                    b.ToTable("game_view_export_cache", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Models.Game", b =>
                {
                    b.HasOne("GamesDatabase.Api.Models.GamePlatform", "Platform")
                        .WithMany("Games")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GamesDatabase.Api.Models.GamePlayedStatus", "PlayedStatus")
                        .WithMany("Games")
                        .HasForeignKey("PlayedStatusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GamesDatabase.Api.Models.GameStatus", "Status")
                        .WithMany("Games")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamesDatabase.Api.Models.User", "User")
                        .WithMany("Games")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");

                    b.Navigation("PlayedStatus");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamesDatabase.Api.Models.GameExportCache", b =>
                {
                    b.HasOne("GamesDatabase.Api.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GamesDatabase.Api.Models.GamePlatform", b =>
                {
                    b.HasOne("GamesDatabase.Api.Models.User", "User")
                        .WithMany("Platforms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamesDatabase.Api.Models.GamePlayWith", b =>
                {
                    b.HasOne("GamesDatabase.Api.Models.User", "User")
                        .WithMany("PlayWiths")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamesDatabase.Api.Models.GamePlayWithMapping", b =>
                {
                    b.HasOne("GamesDatabase.Api.Models.Game", "Game")
                        .WithMany("GamePlayWiths")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesDatabase.Api.Models.GamePlayWith", "PlayWith")
                        .WithMany("GamePlayWiths")
                        .HasForeignKey("PlayWithId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("PlayWith");
                });

            modelBuilder.Entity("GamesDatabase.Api.Models.GamePlayedStatus", b =>
                {
                    b.HasOne("GamesDatabase.Api.Models.User", "User")
                        .WithMany("PlayedStatuses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamesDatabase.Api.Models.GameStatus", b =>
                {
                    b.HasOne("GamesDatabase.Api.Models.User", "User")
                        .WithMany("Statuses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamesDatabase.Api.Models.GameView", b =>
                {
                    b.HasOne("GamesDatabase.Api.Models.User", "User")
                        .WithMany("Views")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamesDatabase.Api.Models.GameViewExportCache", b =>
                {
                    b.HasOne("GamesDatabase.Api.Models.GameView", "GameView")
                        .WithMany()
                        .HasForeignKey("GameViewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameView");
                });

            modelBuilder.Entity("GamesDatabase.Api.Models.Game", b =>
                {
                    b.Navigation("GamePlayWiths");
                });

            modelBuilder.Entity("GamesDatabase.Api.Models.GamePlatform", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("GamesDatabase.Api.Models.GamePlayWith", b =>
                {
                    b.Navigation("GamePlayWiths");
                });

            modelBuilder.Entity("GamesDatabase.Api.Models.GamePlayedStatus", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("GamesDatabase.Api.Models.GameStatus", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("GamesDatabase.Api.Models.User", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Platforms");

                    b.Navigation("PlayWiths");

                    b.Navigation("PlayedStatuses");

                    b.Navigation("Statuses");

                    b.Navigation("Views");
                });
#pragma warning restore 612, 618
        }
    }
}
