// <auto-generated />
using GamesDatabase.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GamesDatabase.Api.Migrations
{
    [DbContext(typeof(GamesDbContext))]
    [Migration("20250913030000_AddLogoAndCoverColumns")]
    partial class AddLogoAndCoverColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            // Esta es una migración simplificada que solo agrega las columnas Logo y Cover
            // El modelo completo se mantiene en el ModelSnapshot
#pragma warning restore 612, 618
        }
    }
}