// <auto-generated />
using System;
using GamesDatabase.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamesDatabase.Api.Migrations
{
    [DbContext(typeof(GamesDbContext))]
    [Migration("20260716055407_AddFavoriteToGame")]
    partial class AddFavoriteToGame
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.BackupSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("BackupHour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(3)
                        .HasColumnName("backup_hour");

                    b.Property<int>("BackupMinute")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("backup_minute");

                    b.Property<string>("BackupType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("full")
                        .HasColumnName("backup_type");

                    b.Property<string>("DestinationPath")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("/backups")
                        .HasColumnName("destination_path");

                    b.Property<string>("FileNamePrefix")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("file_name_prefix");

                    b.Property<string>("FileNameSuffix")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("file_name_suffix");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_run_at");

                    b.Property<string>("LastRunMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_run_message");

                    b.Property<string>("LastRunStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("never")
                        .HasColumnName("last_run_status");

                    b.Property<int>("RetentionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(7)
                        .HasColumnName("retention_count");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("backup_schedule", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.DuplicateGameDismissal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("GameIdA")
                        .HasColumnType("INTEGER")
                        .HasColumnName("game_id_a");

                    b.Property<int>("GameIdB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("game_id_b");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GameIdA");

                    b.HasIndex("GameIdB");

                    b.HasIndex("UserId", "GameIdA", "GameIdB")
                        .IsUnique();

                    b.ToTable("duplicate_game_dismissal", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<int?>("Completion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completion");

                    b.Property<string>("Cover")
                        .HasColumnType("TEXT")
                        .HasColumnName("cover");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("Critic")
                        .HasColumnType("INTEGER")
                        .HasColumnName("critic");

                    b.Property<string>("CriticProvider")
                        .HasColumnType("TEXT")
                        .HasColumnName("critic_provider");

                    b.Property<bool>("Favorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("favorite");

                    b.Property<string>("Finished")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished");

                    b.Property<int?>("Grade")
                        .HasColumnType("INTEGER")
                        .HasColumnName("grade");

                    b.Property<string>("Hero")
                        .HasColumnType("TEXT")
                        .HasColumnName("hero");

                    b.Property<bool?>("IsCheaperByKey")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManuallyCompleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsManuallyCompleted");

                    b.Property<string>("KeyStoreUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Logo")
                        .HasColumnType("TEXT")
                        .HasColumnName("logo");

                    b.Property<int?>("ManualPlaytimeMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("manual_playtime_minutes");

                    b.Property<bool>("ModifiedSinceExport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("modified_since_export");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int?>("PlatformId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("platform_id");

                    b.Property<int?>("PlayedStatusId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("played_status_id");

                    b.Property<string>("Released")
                        .HasColumnType("TEXT")
                        .HasColumnName("released");

                    b.Property<decimal?>("Score")
                        .HasColumnType("TEXT")
                        .HasColumnName("score");

                    b.Property<string>("Started")
                        .HasColumnType("TEXT")
                        .HasColumnName("started");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status_id");

                    b.Property<int?>("SteamAppId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("steam_app_id");

                    b.Property<string>("SteamFinishedLastValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("steam_finished_last_value");

                    b.Property<string>("SteamFinishedRejectedValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("steam_finished_rejected_value");

                    b.Property<string>("SteamFinishedSource")
                        .HasColumnType("TEXT")
                        .HasColumnName("steam_finished_source");

                    b.Property<DateTime?>("SteamFinishedSyncedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("steam_finished_synced_at");

                    b.Property<DateTime?>("SteamLastSynced")
                        .HasColumnType("TEXT")
                        .HasColumnName("steam_last_synced");

                    b.Property<int?>("SteamPlaytime2Weeks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("steam_playtime_2weeks");

                    b.Property<int?>("SteamPlaytimeForever")
                        .HasColumnType("INTEGER")
                        .HasColumnName("steam_playtime_forever");

                    b.Property<string>("SteamStartedRejectedValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("steam_started_rejected_value");

                    b.Property<int?>("Story")
                        .HasColumnType("INTEGER")
                        .HasColumnName("story");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.HasIndex("PlayedStatusId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("game", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.GameExportCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("CoverDownloaded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("cover_downloaded");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("cover_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("game_id");

                    b.Property<bool>("HeroDownloaded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("hero_downloaded");

                    b.Property<string>("HeroUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("hero_url");

                    b.Property<DateTime>("LastExportedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_exported_at");

                    b.Property<bool>("LogoDownloaded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("logo_downloaded");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("logo_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("game_export_cache", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.GameHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action_type");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("changed_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("field");

                    b.Property<int?>("GameId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("game_id");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("game_name");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("old_value");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("game_history_entry", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.GamePlatform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("#ffffff")
                        .HasColumnName("color");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Logo")
                        .HasColumnType("TEXT")
                        .HasColumnName("logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("game_platform", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.GamePlayWith", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("#ffffff")
                        .HasColumnName("color");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("game_play_with", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.GamePlayWithMapping", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("game_id");

                    b.Property<int>("PlayWithId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("play_with_id");

                    b.HasKey("GameId", "PlayWithId");

                    b.HasIndex("PlayWithId");

                    b.ToTable("game_play_with_mapping", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.GamePlayedStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("#ffffff")
                        .HasColumnName("color");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("game_played_status", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.GameReplay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Finished")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("game_id");

                    b.Property<int?>("Grade")
                        .HasColumnType("INTEGER")
                        .HasColumnName("grade");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Released")
                        .HasColumnType("TEXT")
                        .HasColumnName("released");

                    b.Property<int>("ReplayTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("replay_type_id");

                    b.Property<string>("Started")
                        .HasColumnType("TEXT")
                        .HasColumnName("started");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("ReplayTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("game_replay", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.GameReplayType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("#ffffff")
                        .HasColumnName("color");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("ReplayType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("replay_type");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.HasIndex("UserId", "ReplayType", "IsDefault")
                        .IsUnique()
                        .HasFilter("is_default = 1");

                    b.ToTable("game_replay_type", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.GameStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("#ffffff")
                        .HasColumnName("color");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<int>("StatusType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status_type");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.HasIndex("UserId", "StatusType", "IsDefault")
                        .IsUnique()
                        .HasFilter("is_default = 1");

                    b.ToTable("game_status", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.GameView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("FiltersJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("filters_json");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_public");

                    b.Property<bool>("ModifiedSinceExport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("modified_since_export");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SortingJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("sorting_json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("game_view", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.GameViewExportCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ConfigurationHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("configuration_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("GameViewId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("game_view_id");

                    b.Property<DateTime>("LastExportedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_exported_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GameViewId")
                        .IsUnique();

                    b.ToTable("game_view_export_cache", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<bool>("Revoked")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revoked");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.SteamAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Achieved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("achieved");

                    b.Property<string>("ApiName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("api_name");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<int?>("GameId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("game_id");

                    b.Property<bool>("Hidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("hidden");

                    b.Property<string>("IconGrayUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("icon_gray_url");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("icon_url");

                    b.Property<DateTime>("LastSynced")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_synced");

                    b.Property<int>("SteamAppId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("steam_app_id");

                    b.Property<DateTime?>("UnlockTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("unlock_time");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId", "SteamAppId", "ApiName")
                        .IsUnique();

                    b.ToTable("steam_achievement", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.SteamAppCache", b =>
                {
                    b.Property<int>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("app_id");

                    b.Property<string>("BackgroundImageUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("background_image_url");

                    b.Property<string>("CategoriesJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("categories_json");

                    b.Property<string>("Developer")
                        .HasColumnType("TEXT")
                        .HasColumnName("developer");

                    b.Property<string>("GenresJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("genres_json");

                    b.Property<string>("HeaderImageUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("header_image_url");

                    b.Property<bool>("IsFree")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_free");

                    b.Property<DateTime>("LastFetched")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_fetched");

                    b.Property<int?>("MetacriticScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("metacritic_score");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Price")
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT")
                        .HasColumnName("publisher");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("release_date");

                    b.HasKey("AppId");

                    b.ToTable("steam_app_cache", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.SteamMatchDismissal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("game_id");

                    b.Property<int>("SteamAppId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("steam_app_id");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId", "SteamAppId", "GameId")
                        .IsUnique();

                    b.ToTable("steam_match_dismissal", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role");

                    b.Property<string>("ScoreProvider")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("score_provider");

                    b.Property<bool>("ShowPriceComparisonIcon")
                        .HasColumnType("INTEGER")
                        .HasColumnName("show_price_comparison_icon");

                    b.Property<string>("SteamAvatarUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("steam_avatar_url");

                    b.Property<string>("SteamId")
                        .HasColumnType("TEXT")
                        .HasColumnName("steam_id");

                    b.Property<DateTime?>("SteamLinkedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("steam_linked_at");

                    b.Property<string>("SteamNickname")
                        .HasColumnType("TEXT")
                        .HasColumnName("steam_nickname");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UseScoreColors")
                        .HasColumnType("INTEGER")
                        .HasColumnName("use_score_colors");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.BackupSchedule", b =>
                {
                    b.HasOne("GamesDatabase.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.DuplicateGameDismissal", b =>
                {
                    b.HasOne("GamesDatabase.Api.Domain.Entities.Game", "GameA")
                        .WithMany()
                        .HasForeignKey("GameIdA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesDatabase.Api.Domain.Entities.Game", "GameB")
                        .WithMany()
                        .HasForeignKey("GameIdB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesDatabase.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameA");

                    b.Navigation("GameB");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.Game", b =>
                {
                    b.HasOne("GamesDatabase.Api.Domain.Entities.GamePlatform", "Platform")
                        .WithMany("Games")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GamesDatabase.Api.Domain.Entities.GamePlayedStatus", "PlayedStatus")
                        .WithMany("Games")
                        .HasForeignKey("PlayedStatusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GamesDatabase.Api.Domain.Entities.GameStatus", "Status")
                        .WithMany("Games")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamesDatabase.Api.Domain.Entities.User", "User")
                        .WithMany("Games")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");

                    b.Navigation("PlayedStatus");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.GameExportCache", b =>
                {
                    b.HasOne("GamesDatabase.Api.Domain.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.GameHistoryEntry", b =>
                {
                    b.HasOne("GamesDatabase.Api.Domain.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GamesDatabase.Api.Domain.Entities.User", "User")
                        .WithMany("HistoryEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.GamePlatform", b =>
                {
                    b.HasOne("GamesDatabase.Api.Domain.Entities.User", "User")
                        .WithMany("Platforms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.GamePlayWith", b =>
                {
                    b.HasOne("GamesDatabase.Api.Domain.Entities.User", "User")
                        .WithMany("PlayWiths")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.GamePlayWithMapping", b =>
                {
                    b.HasOne("GamesDatabase.Api.Domain.Entities.Game", "Game")
                        .WithMany("GamePlayWiths")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesDatabase.Api.Domain.Entities.GamePlayWith", "PlayWith")
                        .WithMany("GamePlayWiths")
                        .HasForeignKey("PlayWithId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("PlayWith");
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.GamePlayedStatus", b =>
                {
                    b.HasOne("GamesDatabase.Api.Domain.Entities.User", "User")
                        .WithMany("PlayedStatuses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.GameReplay", b =>
                {
                    b.HasOne("GamesDatabase.Api.Domain.Entities.Game", "Game")
                        .WithMany("GameReplays")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesDatabase.Api.Domain.Entities.GameReplayType", "ReplayType")
                        .WithMany("Replays")
                        .HasForeignKey("ReplayTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamesDatabase.Api.Domain.Entities.User", "User")
                        .WithMany("Replays")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("ReplayType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.GameReplayType", b =>
                {
                    b.HasOne("GamesDatabase.Api.Domain.Entities.User", "User")
                        .WithMany("ReplayTypes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.GameStatus", b =>
                {
                    b.HasOne("GamesDatabase.Api.Domain.Entities.User", "User")
                        .WithMany("Statuses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.GameView", b =>
                {
                    b.HasOne("GamesDatabase.Api.Domain.Entities.User", "User")
                        .WithMany("Views")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.GameViewExportCache", b =>
                {
                    b.HasOne("GamesDatabase.Api.Domain.Entities.GameView", "GameView")
                        .WithMany()
                        .HasForeignKey("GameViewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameView");
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("GamesDatabase.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.SteamAchievement", b =>
                {
                    b.HasOne("GamesDatabase.Api.Domain.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GamesDatabase.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.SteamMatchDismissal", b =>
                {
                    b.HasOne("GamesDatabase.Api.Domain.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesDatabase.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.Game", b =>
                {
                    b.Navigation("GamePlayWiths");

                    b.Navigation("GameReplays");
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.GamePlatform", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.GamePlayWith", b =>
                {
                    b.Navigation("GamePlayWiths");
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.GamePlayedStatus", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.GameReplayType", b =>
                {
                    b.Navigation("Replays");
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.GameStatus", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("GamesDatabase.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("HistoryEntries");

                    b.Navigation("Platforms");

                    b.Navigation("PlayWiths");

                    b.Navigation("PlayedStatuses");

                    b.Navigation("ReplayTypes");

                    b.Navigation("Replays");

                    b.Navigation("Statuses");

                    b.Navigation("Views");
                });
#pragma warning restore 612, 618
        }
    }
}
